/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlockPageHeader: typeof import('./components/blockPage/BlockPageHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FailTip: typeof import('./components/blockPage/FailTip.vue')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
    PassComponent: typeof import('./components/blockPage/PassComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
